# Generated by Django 2.2.4 on 2019-11-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employeemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=30)),
                ('disease', models.CharField(max_length=30)),
                ('patient_contact_no', models.IntegerField()),
                ('doc_id', models.ManyToManyField(to='app.doctorModel')),
            ],
        ),
    ]
