# Generated by Django 2.2.4 on 2019-12-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_patient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.AutoField(default=False, primary_key=True, serialize=False),
        ),
    ]
